apiVersion: v2
name: sweatshop-creator
description: Helm chart for Kubernetes
type: application
version: v0.1.24
appVersion: v0.1.24
dependencies:
  - name: sthings-helm-toolkit
    version: 2.4.42
    repository: oci://eu.gcr.io/stuttgart-things
  - name: redis
    version: 17.11.6
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: yacht-tekton-resources
    version: v0.47.10
    repository: oci://eu.gcr.io/stuttgart-things
    condition: tektonResources.enabled
