# Default values for stageTime-creator.
namespace: sweatshop
tektonResources:
  enabled: false
pipelineRuns:
  enableRuns: false
  runs:
    buildHelmChart:
      name: sws-creator-helm
      addRandomDateToRunName: false
      namespace: tekton-cd
      kind: Pipeline
      ref: package-publish-helmchart
      params:
        git-repo-url: git@github.com:stuttgart-things/stageTime-creator.git
        git-revision: main
        gitWorkspaceSubdirectory: /helm/sws-c
        helm-chart-name: stagetime-creator
        helm-chart-tag: v0.1.55
        helm-chart-path: helm
        registry: scr.app.4sthings.tiab.ssc.sva.de
        working-image: "eu.gcr.io/stuttgart-things/sthings-k8s:1.127.2"
      workspaces:
        ssh-credentials:
          workspaceKind: secret
          workspaceRef: github-ssh
        source:
          workspaceKind: persistentVolumeClaim
          workspaceRef: helm-workspace
        dockerconfig:
          workspaceKind: secret
          workspaceRef: scr-labda-vsphere
    buildKanikoImage:
      name: sws-creator-kaniko
      addRandomDateToRunName: false
      namespace: tekton-cd
      kind: Pipeline
      ref: build-kaniko-image
      params:
        gitRepoUrl: git@github.com:stuttgart-things/stageTime-creator.git
        git-revision: main
        context: /kaniko/sws-creator
        gitWorkspaceSubdirectory: /kaniko/sws-creator
        image: scr.app.4sthings.tiab.ssc.sva.de/sweatshop/creator
        tag: 23.0731.1856-v0.1.55
        registry: eu.gcr.io
        dockerfile: Dockerfile
      workspaces:
        ssh-credentials:
          workspaceKind: secret
          workspaceRef: github-ssh
        shared-workspace:
          workspaceKind: persistentVolumeClaim
          workspaceRef: kaniko-workspace
        dockerconfig:
          workspaceKind: secret
          workspaceRef: scr-labda-vsphere
redis:
  enabled: false
  # sentinel:
  #   enabled: true
  # master:
  #   service:
  #     type: ClusterIP
  #   persistence:
  #     enabled: false
  #     medium: ""
  # replica:
  #   replicaCount: 1
  #   persistence:
  #     enabled: false
  #     medium: ""
  # auth:
  #   password: just4dev
# secrets:
#   redis:
#     name: redis
#     labels:
#       app.kubernetes.io/component: creator
#       app.kubernetes.io/created-by: stagetime-creator
#       app.kubernetes.io/part-of: sweatshop
#     secretKVs:
#       REDIS_PASSWORD: <path:apps/data/sweatshop#redisPassword>

configmaps:
  # creator:
  #   TEMPLATE_PATH: /templates
  #   REDIS_STREAM: sweatshop:manifests
  #   REDIS_SERVER: sweatshop-informer-redis-headless.sweatshop.svc.cluster.local
  #   REDIS_PORT: "6379"
  manifest-templates:
    inventory.gotmpl: |
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: {{`{{ .name }}`}}
        namespace: {{`{{ .namespace }}`}}
      data:
        inventory: |{{`{{ range $name, $value := .inventory }}`}}
          [{{`{{ $name }}`}}]{{`{{ range $value }}`}}
          {{`{{ . }}`}}{{`{{ end }}`}}
          {{`{{ end }}`}}

deployment:
  name: stagetime-creator
  volumes:
    manifest-templates:
      volumeKind: configMap
  labels:
    app: stagetime-creator
  selectorLabels:
    app: stagetime-creator
  allowPrivilegeEscalation: "false"
  privileged: "false"
  runAsNonRoot: "false"
  readOnlyRootFilesystem: "true"
  serviceAccount: stagetime-creator
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  containers:
    stagetime-creator:
      volumeMounts:
        manifest-templates:
          mountPath: /templates/
          volumeKind: emptyDir
      image: eu.gcr.io/stuttgart-things/stagetime-creator
      replicaCount: 1
      imagePullPolicy: Always
      tag: 23.0731.1856-v0.1.55
      securityContext:
        capabilities: {}
# RBAC
serviceAccounts:
  stagetime-creator:
    labels:
      app: stagetime-creator
roles:
  stagetime-creator:
    labels:
      app: stagetime-creator
    rules:
      - apiGroups:
          - ""
        resources:
          - pods
        verbs:
          - get
          - list
          - watch
          - create
          - patch
          - delete
      - apiGroups:
          - "batch"
        resources:
          - jobs
        verbs:
          - get
          - list
          - watch
          - create
          - patch
          - delete
      - apiGroups:
          - ""
        resources:
          - configmaps
        verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
roleBindings:
  stagetime-creator:
    labels:
      app: stagetime-creator
    roleRef:
      kind: Role
      name: stagetime-creator
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: stagetime-creator
        namespace: sweatshop
clusterRoles:
  stagetime-creator:
    labels:
      app: stagetime-creator
    rules:
      - apiGroups:
          - ""
        resources:
          - namespaces
        verbs:
          - get
          - list
      - apiGroups:
          - "batch"
        resources:
          - jobs
        verbs:
          - get
          - list
          - create
          - patch
          - delete
      - apiGroups:
          - ""
        resources:
          - configmaps
        verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
clusterRoleBindings:
  stagetime-creator:
    roleRef:
      kind: ClusterRole
      name: stagetime-creator
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: stagetime-creator
        namespace: sweatshop
