# Default values for sweatShop-creator.
namespace: sweatshop

configmaps:
  configuration:
    TEMPLATE_PATH: /templates
    TEMPLATE_NAME: job.yaml.gotmpl
    REDIS_STREAM: "sweatshop:manifests"

  manifest-templates:
    job.yaml.gotmpl: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: {{ .Name }}
        namespace: machine-shop

deployment:
  name: sweatshop-creator
  volumes:
    manifest-templates:
      volumeKind: configMap
  labels:
    app: sweatshop-creator
  selectorLabels:
    app: sweatshop-creator
  allowPrivilegeEscalation: "false"
  privileged: "false"
  runAsNonRoot: "false"
  readOnlyRootFilesystem: "true"
  serviceAccount: sweatshop-creator
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  containers:
    sweatshop-creator:
      volumeMounts:
        manifest-templates:
          mountPath: /templates/
          volumeKind: emptyDir
      image: eu.gcr.io/stuttgart-things/sweatshop-creator
      replicaCount: 1
      imagePullPolicy: Always
      tag: 23.0622.1132-0.3.11
      securityContext:
        capabilities: {}

# RBAC
serviceAccounts:
  sweatshop-creator:
    labels:
      app: sweatshop-creator

roles:
  sweatshop-creator:
    labels:
      app: sweatshop-creator
    rules:
      - apiGroups:
          - ""
        resources:
          - pods
        verbs:
          - get
          - list
          - watch
          - create
      - apiGroups:
          - "batch"
        resources:
          - jobs
        verbs:
          - get
          - list
          - watch
          - create

roleBindings:
  sweatshop-creator:
    labels:
      app: sweatshop-creator
    roleRef:
      kind: Role
      name: sweatshop-creator
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: sweatshop-creator
        namespace: yacht

clusterRoles:
  list-all-namespaces:
    labels:
      app: sweatshop-creator
    rules:
      - apiGroups:
          - ""
        resources:
          - namespaces
        verbs:
          - get
          - list

clusterRoleBindings:
  list-all-namespaces:
    roleRef:
      kind: ClusterRole
      name: list-all-namespaces
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: sweatshop-creator
        namespace: yacht
