apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: package-publish-helmchart
  name: sws-creator-helm-${ARGOCD_APP_REVISION}
  namespace: tekton-cd
spec:
  params:
    - name: git-repo-url
      value: 'git@github.com:stuttgart-things/sweatShop-creator.git'
    - name: git-revision
      value: main
    - name: gitWorkspaceSubdirectory
      value: /helm/swsc
    - name: helm-chart-name
      value: sweatshop-creator
    - name: helm-chart-path
      value: helm
    - name: helm-chart-tag
      value: ${ARGOCD_APP_REVISION}
    - name: registry
      value: scr.app.4sthings.tiab.ssc.sva.de
    - name: working-image
      value: 'eu.gcr.io/stuttgart-things/sthings-k8s:1.127.2'
  pipelineRef:
    name: package-publish-helmchart
  taskRunTemplate:
    serviceAccountName: default
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: dockerconfig
      secret:
        secretName: scr-labda-vsphere
    - name: source
      persistentVolumeClaim:
        claimName: helm-workspace
    - name: ssh-credentials
      secret:
        secretName: github-ssh