apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sweat-shop-creator-deployment
  namespace: argocd
spec:
  project: app
  destination:
    name: dev11
    namespace: sweatshop
  source:
    repoURL: eu.gcr.io/stuttgart-things
    chart: sweatshop-creator
    targetRevision: v0.1.23
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            namespace: sweatshop
            redis:
              enabled: false
            configmaps:
              creator:
                TEMPLATE_PATH: /templates
                TEMPLATE_NAME: ansible-job.yaml.gotmpl
                REDIS_STREAM: sweatshop:manifests
                REDIS_SERVER: redis-sweatshop-deployment-headless.sweatshop-redis.svc.cluster.local
                REDIS_PORT: "6379"
                REDIS_PASSWORD: <path:apps/data/sweatshop#redisPassword>
            clusterRoleBindings:
              sweatshop-creator:
                subjects[0]:
                  namespace: sweatshop
            roleBindings:
              sweatshop-creator:
                subjects[0]:
                  namespace: sweatshop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
