---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tkn-sweat-shop-creator-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: app
  destination:
    name: dev11
    namespace: tekton-cd
  source:
    repoURL: eu.gcr.io/stuttgart-things
    chart: yacht-tekton-resources
    targetRevision: v0.47.10
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            enableRuns: true
            runs:
              buildHelmChart:
                name: build-sws-creator-helm-2
                addRandomDateToRunName: false
                namespace: tekton-cd
                kind: Pipeline
                ref: package-publish-helmchart
                params:
                  git-repo-url: git@github.com:stuttgart-things/sweatShop-creator.git
                  git-revision: main
                  gitWorkspaceSubdirectory: /helm/swsc
                  helm-chart-name: sweat-shop-creator
                  helm-chart-tag: 0.8.15
                  helm-chart-path: helm
                  registry: scr.app.4sthings.tiab.ssc.sva.de
                  working-image: "eu.gcr.io/stuttgart-things/sthings-k8s:1.127.2"
                workspaces:
                  ssh-credentials:
                    workspaceKind: secret
                    workspaceRef: github-ssh
                  source:
                    workspaceKind: persistentVolumeClaim
                    workspaceRef: helm-workspace
                  dockerconfig:
                    workspaceKind: secret
                    workspaceRef: scr-labda-vsphere
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
